### ISSUE TITLE
Location of merchant-kit-sdk.jar

### ISSUE THREAD

**Issue by pitw** [Devalfaz/worldline_pg#1]
Where should I find the **merchant-kit-sdk.jar** ?

Checked the SDKs but not sure which one is the right one. Could you provide a link ?

**Comment by Devalfaz** [comment]
Are you using PG provided by Worldline India Private Limited which provides another standard of implementation? If not sorry to inform you that this is that. **merchant-kit-sdk.jar** is provided by them and i couldn't add that library to my code since maybe it is a violation of terms to share that. Hope you understand.

You could verify if we are using the same portal by checking this link

https://cgt.in.worldline-solutions.com/MerchantPortal

**Comment by pitw** [comment]
Don't know if I should cry or laught ;)
I was looking for a flutter solution for [Worldline](https://de.worldline.com/de/home.html)
Same name, same function and even similar structure (merchantId, etc...) - but cleary not the the same company or API.

Thanks for your answer and for providing this to the flutter community - looks like I have to develop this for Worldline Europe by myself.
